version: '3'
services:
  app:
    image: deepakdocker04/template:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: kannan
      MYSQL_DATABASE: test